# Generated by Django 5.1.4 on 2025-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cost_isdeleted_income_isdeleted_output_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
