# Generated by Django 5.1.4 on 2025-04-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_payments',
            name='price',
            field=models.FloatField(verbose_name='💲Maosh'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff', verbose_name='🧍\u200d♂️Hodimlar'),
        ),
    ]
